### ISSUE TITLE
Make the exporter more generic

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/cost-exporter#4]
@stephanlindauer What do you think about making this exporter more generic (ie an `aws-exporter`)? If I understand correctly, this exporter scrapes data from the API with bypassing CloudWatch. We could also use this for other stuff.

A specific example: We somehow got some spot requests in a weird state, where they are cancelled but still running. Having metrics about this in Prometheus would be quite nice.

For example having this data in AWS:

```
$ aws ec2 describe-spot-instance-requests | jq '.SpotInstanceRequests[] | .Status.Code'
"fulfilled"
"request-canceled-and-instance-running"
"fulfilled"
"fulfilled"
"fulfilled"
"fulfilled"
"fulfilled"
"fulfilled"
"request-canceled-and-instance-running"
"fulfilled"
"fulfilled"
"fulfilled"
"request-canceled-and-instance-running"
"request-canceled-and-instance-running"
```

Could result in metrics like this:

```
aws_spot_instance_request_states_total{state="active", code="fulfilled"} 10
aws_spot_instance_request_states_total{state="cancelled", code="request-canceled-and-instance-running"} 4
```

I am pretty sure we will also find other interesting data to export later.

**Comment by stephanlindauer** [comment]
@svenwltr sounds good. :)

**Comment by svenwltr** [comment]
@stephanlindauer You already did this, right?
